channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pytorch=1.9.1=*cuda* # Need to specifically request cuda version
  - torchvision=0.10.1
  - ipykernel=6.29.*
  # - mkl<=2024.0 # Need to downgrade mkl for compatibility with pytorch
  - pip<24.1
  # Install pip requirements with `pip install -r requirements.txt`
